[phases.setup]
nixPkgs = ["nodejs", "nodePackages.pnpm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run seed && npm run seedBlots && npm start"
